# The first instruction is what image we want to base our container on
# We Use an official Python runtime as a parent image
FROM python:3.8.2

# The enviroment variable ensures that the python output is set straight
# to the terminal with out buffering it first
ENV PYTHONUNBUFFERED 1

# create root directory for our project in the container
# RUN mkdir /SportsRoom

# Set the working directory to /SportsRoom
# WORKDIR /SportsRoom

# The following set of commands run a script that installs the redis-server, by building from the source files.
# Only the binary files are created and put back in /SportsRoom. So while running the redis-server, run accordingly.
ADD . /SportsRoom
WORKDIR /SportsRoom
RUN /bin/bash redis_install_script.sh
WORKDIR /SportsRoom

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt
