# Generated by Django 2.1.5 on 2020-05-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsEquipment', '0013_ground_who_booked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addGround',
        ),
    ]
